### ISSUE TITLE
Snippet for documention is not displayed

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule-vscode#25]
**Description of the issue**
Snippet for documention is not displayed:
![image](https://user-images.githubusercontent.com/4894452/59764889-0ac95c00-929d-11e9-8c4c-788c7a1673a1.png)

Extension version v0.3.0
VSCode version 1.35.1
Windows 10 Fr, 1803

[edit]
Is the [prefix ](https://github.com/BernieWhite/PSRule-vscode/blob/master/snippets/markdown.json#L3)duplicate ?

**Comment by BernieWhite** [comment]
@LaurentDardenne Documentation is done in markdown. So try within a markdown file with a `.md` extension.

**Comment by LaurentDardenne** [comment]
> So try within a markdown file with a .md extension.

it works better like that ;-)
Thanks.
